### PR TITLE
Enable ARM OSX

### PR DESCRIPTION
**Pull request by ax3l**
Enable support for OSX ARM builds.

Needed for https://github.com/conda-forge/openpmd-api-feedstock/pull/66

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged): not needed since only adding a new build platform
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge/catch2 new arch migration to Apple X1 (macOS on ARM) ready for merge :tada:

**Comment by tdegeus** [comment]
Thanks!

**Pull request merged**
