### PR TITLE
v2.13.4 with OSx fix

### PR DESCRIPTION
**Pull request by tdegeus**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tdegeus** [comment]
Do you agree to patch @mjscosta ? It implies that the patches will have to be removed on the next release

**Comment by mjscosta** [comment]
Hi @tdegeus , I agree with the patch.

Unfortunately I don't have the time to maintain the package.
Adding the patches the package will require maintenance for futures upstream releases.

Did you manage to get your PR accepted in the upstream catch2 repo ?
Do you really need the update ?
Can you maintain the future release ?

Thanks for the contribution and the effort!

**Review by mjscosta — APPROVED** [review]

**Comment by tdegeus** [comment]
Hi @mjscosta ! No worries, I will remove the patches on the next release. I maintain so many packages that I don't mind doing it for this as well. The patches here are in fact what was merged upstream, so they just put this feedstock up to speed with the latests commit upstream

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
