### PR TITLE
Fix linux build

### PR DESCRIPTION
**Pull request by mjscosta**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by allanleal** [comment]
Looks good to me - replacing those `test -f <file>` commands by a proper test source file that gets compiled and executed.

**Comment by allanleal** [comment]
For osx, it is failing when configuring the test project:

~~~
-- The C compiler identification is Clang 4.0.1
-- The CXX compiler identification is Clang 4.0.1
-- Check for working C compiler: $PREFIX/bin/x86_64-apple-darwin13.4.0-clang
-- Check for working C compiler: $PREFIX/bin/x86_64-apple-darwin13.4.0-clang -- broken
~~~

but when configuring the build of the lib itself:

~~~
-- The CXX compiler identification is Clang 4.0.1
-- Check for working CXX compiler: $BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++
-- Check for working CXX compiler: $BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /Users/vsts/agent/2.147.1/work/1/a/miniconda/bin/python (found version "3.7.1") 
-- Enabling C++11
~~~

There is no issue.

**Comment by mjscosta** [comment]
Failing OSX, needs fix.
Merging so that windows and linux packages become properly available.

**Comment by mjscosta** [comment]
@allanleal OSX is failing, I don't have time to check and fix it, and at the moment I only need Windows and Linux. I case you need OSX, feel free to contribute. :)

**Comment by allanleal** [comment]
Excellent @mjscosta - thanks a lot for this. `conda search catch2` now ouputs (in Linux):

~~~
Loading channels: done
# Name                       Version           Build  Channel             
catch2                         2.6.1      h6bb024c_1  conda-forge         
catch2                         2.6.1      h6bb024c_3  conda-forge         
~~~

I'll see if I can fix for OSX soon.

**Pull request merged**
