### PR TITLE
Arch migration

### PR DESCRIPTION
**Pull request by gabm**
Since I accidentially closed and re-opened #28, the bot does not re-create the PR. @beckermr told me, that I have to upgrade manually.

So I edited `conda-forge.yml` and re-rendered.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gabm** [comment]
@conda-forge-admin, please restart ci¶

**Comment by gabm** [comment]
@mjscosta this is ready... would you pls merge?

**Comment by mjscosta** [comment]
Thanks for your contribution!!

**Comment by mjscosta** [comment]
you forgot to add yourself as a maintainer. If you agree I will add you later.

**Comment by gabm** [comment]
yes of course, please go ahead...

**Pull request merged**
