### PR TITLE
Upgrading to latest version; Adding maintainer

### PR DESCRIPTION
**Pull request by tdegeus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by tdegeus** [comment]
Personally I think that the tests should not have to be run here. It should be in the library itself. Anyway, I think that the failing travis can be accepted from now. Correct @conda-forge/help-c-cpp ?

**Comment by mjscosta** [comment]
Hi @tdegeus, the purpose of tests is to validate that Catch is properly installed in the conda environment, in this particular package they happen to be the same tests as the upstream library. Without them there is no way to identify future issues with the packaging and would possibly break the package in an unnoticed manner.

**Comment by mjscosta** [comment]
Any suggestion for a fix to get all architectures supported passing ?

**Comment by tdegeus** [comment]
Thanks for upgrading. This can now be closed

**Pull request closed without merging**
