### PR TITLE
Fix linux and osx build

### PR DESCRIPTION
**Pull request by allanleal**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by allanleal** [comment]
Sorry, I think this should be requested to your fork @mjscosta .
This PR fixes paths for installed cmake files in linux.

**Comment by allanleal** [comment]
I'll keep this just to see if the issues go away, then delete this duplicate PR. I've already made a PR to your fork.

**Comment by mjscosta** [comment]
@allanleal Thanks for your contribution.

Despite that your solution indeed fixes the tests, I don't think it is the best one, and please let me know if I am mistaken.

I've looked up where most of "*.cmake" files are being stored in conda packages, and I found them to be in:

${PREFIX}/lib/cmake
${PREFIX}/share/cmake/

Here it is described for OSX and Linux and Windows which are the search directories for the find_package.

```
 The tables below show the directories searched. Each entry is meant for installation trees following Windows (W), UNIX (U), or Apple (A) conventions:

<prefix>/                                                       (W)
<prefix>/(cmake|CMake)/                                         (W)
<prefix>/<name>*/                                               (W)
<prefix>/<name>*/(cmake|CMake)/                                 (W)
<prefix>/(lib/<arch>|lib*|share)/cmake/<name>*/                 (U)
<prefix>/(lib/<arch>|lib*|share)/<name>*/                       (U)
<prefix>/(lib/<arch>|lib*|share)/<name>*/(cmake|CMake)/         (U)
<prefix>/<name>*/(lib/<arch>|lib*|share)/cmake/<name>*/         (W/U)
<prefix>/<name>*/(lib/<arch>|lib*|share)/<name>*/               (W/U)
<prefix>/<name>*/(lib/<arch>|lib*|share)/<name>*/(cmake|CMake)/ (W/U)

On systems supporting OS X Frameworks and Application Bundles the following directories are searched for frameworks or bundles containing a configuration file:

<prefix>/<name>.framework/Resources/                    (A)
<prefix>/<name>.framework/Resources/CMake/              (A)
<prefix>/<name>.framework/Versions/*/Resources/         (A)
<prefix>/<name>.framework/Versions/*/Resources/CMake/   (A)
<prefix>/<name>.app/Contents/Resources/                 (A)
<prefix>/<name>.app/Contents/Resources/CMake/           (A)
```

So I think, depite of being a valid path, I will check on how to add it to `lib/cmake/` and add a test with cmake and a test.cpp, to validate that it builds and the cmake targets are properly found and resolved by cmake.

I will merge your PR, and later perform those improvements. Please let me know if you agree.

**Comment by allanleal** [comment]
Hi @mjscosta 

In linux, sometimes the library output path is `lib64` instead of just `lib`. catch2 is probably using `CMAKE_INSTALL_LIBDIR` variable that is created by [`GNUInstallDirs`](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) module.

All I did in this PR was:

~~~
~~~

**Comment by allanleal** [comment]
Awesome - thanks @mjscosta 

Do you know how long it takes for this to be available in conda-forge?

**Comment by mjscosta** [comment]
After the merge and build it will be available.
But I've tested your solution, depite passing the tests it does not work in my linux which is 64 bit.
So cmake does not find the package, I dont know why the CI linux is installing in lib64 and my (ubuntu 16.04 64 bit) is installing in lib.

**Comment by allanleal** [comment]
We could try forcing cmake to always output this in a lib dir instead of 
lib64. I'll check this tomorrow. That was just a quick and dirt solution 
for the recipe to build successfully, but not a robust fix.

**Pull request merged**
